---
- hosts: all

  vars_files:
  - var.yml

  tasks:

  - name: Install cloudera rpms
    action: yum pkg={{item}} state=present
    with_items:
    - mysql
    - epel-release
    - libselinux-python
    - mlocate
    - wget
    - oracle-j2sdk1.7

